/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings --include-runtime false` (hash: 502e2034a04451831617b45e933366c8)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env {}
}
interface CloudflareBindings extends Cloudflare.Env {}
